export const SCREENS ={
    SPLASH_SCREEN: 'SplashScreen',
    LOGIN_SCREEN: 'LoginScreen',
    HOME_SCREEN: 'HomeScreen',
    DAILY_PROJECT_LIST: 'DailyProjectList',
    DAILY_ENTRY_PREVIEW: 'DailyEntryPreview',
    DAILY_DIARY_PREVIEW: 'DailyDiaryPreview',
    DAILY_73: 'Daily73',
    DAILY_84: 'Daily84',
    DAILY_85: 'Daily85',
    DAILY_86: 'Daily86',
    WEEKLY_INVOICE_LIST: 'WeeklyInvoiceList',
    VISITOR_DETAILS: 'VisitorDetails',
    EQUIMENTS_DETAILS: 'EquimentsDetails',
    LABOUR_DETAILS: 'LabourDetails',
    DESCRIPTION_DETAILS: 'DescriptionDetails',
    WEEKLY_REPORT_CONFIRM: 'WeeklyReportConfirm',
    WORK_FROM_ENTRY: 'WorkFromEntry',
    ADD_COMPANY_EMAIL:'AddCompanyEmailScreen',
    PHOTO_FILES_SELECTION:'PhotoFilesSelection',
    IMAGE_VIEWER:'ImageViewer',
    PROJECT_LIST_SCREEN:'ProjectListScreen',
    FORGOT_PASSWORD:'ForgotPassword',
    VERIFY_CODE_SCREEN:'VerifyCodeScreen',
    RESET_PASSWORD_SCREEN:'ResetPasswordScreen',
    REGISTER_SCREEN:'RegisterScreen',
    BASELINE_SCHEDULE_LIST:'BaseLineScheduleList',
    CREATE_SCHEDULE:'CreateSchedule',
    PHOTO_FILES:'PhotoFiles',
    VIEW_ALL_PHOTO:'ViewAllPhoto',
    JOB_HAZARD_ANALYSIS:'JobHazardAnalysis',
    CREATE_JOB_HAZARD:'CreateJobHazard',
    DAILY_ENTRY_SCREEN:'DailyEntryScreen',
WEEKLY_ENTRY_SCREEN:'WeeklyEntryScreen',
DAIRY_ENTRY_SCREEN:'DairyEntryScreen',
CREATE_EXPENSE_SCREEN:'CreateExpenseScreen',
JOB_HAZARD_REVIEW:'JobHazardReview',
START_MILEAGE_SCREEN:'StartMileageScreen',
    MAIN_TABS: 'MainTabs',
    DAILY_FORM_REPORT_SCREEN:'DailyFormReportScreen'

}