export const initializeWeeklyEntry = {
    startDate: '',
    endDate: '',
    projectId: '',
    userId: '',
    projectName: '',
    projectNumber: '',
    contractNumber: '',
    owner: '',
    cityProjectManager: '',
    consultantProjectManager: '',
    contractProjectManager: '',
    contractorSiteSupervisorOnshore: '',
    contractorSiteSupervisorOffshore: '',
    contractAdministrator: '',
    supportCA: '',
    siteInspector: [''],
    isChargeable: true,
    inspectorTimeIn: '',
    inspectorTimeOut: '',
    reportDate: '',
    images: [],
    logo: '',
    dailyDiaries:[],
    dailyEntries:[],
    signature :''
};
